package handler

import (
	"encoding/base64"
	"encoding/json"
	"io"
	"net/http"
	"os"
	"strings"

	dotenv "github.com/joho/godotenv"
)

func CurrentPlaying(w http.ResponseWriter, r *http.Request) {
	dotenv.Load()
	svg := r.URL.Query().Get("svg") == "true"
	var SPOTIFY_COOKIE = os.Getenv("SPOTIFY_COOKIE")

	if SPOTIFY_COOKIE == "" {
		http.Error(w, `{"error": "missing 'SPOTIFY_COOKIE', set your 'sp_dc' cookie from open.spotify.com"}`, http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Access-Control-Allow-Origin", "*")

	currentPlaying, err := getCurrentPlaying(SPOTIFY_COOKIE, svg)
	if err != nil {
		http.Error(w, `{"error": "failed to get current playing song: `+err.Error()+`"}`, http.StatusInternalServerError)
		return
	}

	if svg {
		w.Header().Set("Content-Type", "image/svg+xml")
	} else {
		w.Header().Set("Content-Type", "application/json")
	}

	w.Write(currentPlaying)
}

func getCurrentPlaying(cookie string, svg bool) ([]byte, error) {
	client := &http.Client{}
	req, err := http.NewRequest("GET", "https://open.spotify.com/get_access_token", nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("cookie", "sp_dc="+cookie)
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()
	var respBody struct {
		AccessToken string `json:"accessToken"`
		IsAnonymous bool   `json:"isAnonymous"`
	}

	json.NewDecoder(resp.Body).Decode(&respBody)

	req, _ = http.NewRequest("GET", "https://api.spotify.com/v1/me/player/currently-playing", nil)
	req.Header.Set("Authorization", "Bearer "+respBody.AccessToken)

	resp, err = client.Do(req)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()

	var currentTrack CurrentTrack
	json.NewDecoder(resp.Body).Decode(&currentTrack)

	result := map[string]interface{}{
		"timestamp":   currentTrack.Timestamp,
		"progress_ms": currentTrack.ProgressMs,
		"title":       currentTrack.Item.Name,
		"duration_ms": currentTrack.Item.DurationMs,
		"url":         currentTrack.Item.ExternalUrls.Spotify,
		"is_playing":  currentTrack.IsPlaying,
	}

	if len(currentTrack.Item.Artists) > 0 {
		result["artists"] = func() string {
			var artists []string
			for _, artist := range currentTrack.Item.Artists {
				artists = append(artists, artist.Name)
				if len(artists) >= 2 {
					break
				}
			}
			return strings.Join(artists, ", ")
		}()
	}

	if len(currentTrack.Item.Album.Images) > 0 {
		result["image"] = currentTrack.Item.Album.Images[0].URL
	}

	if svg {
		return []byte(createSpotifyWidget(result)), nil
	}

	return json.MarshalIndent(result, "", "  ")
}

type CurrentTrack struct {
	Timestamp  int64 `json:"timestamp"`
	ProgressMs int   `json:"progress_ms"`
	Item       struct {
		Album struct {
			Images []struct {
				URL string `json:"url"`
			} `json:"images"`
		} `json:"album"`
		Artists []struct {
			Name string `json:"name"`
		} `json:"artists"`
		DurationMs   int `json:"duration_ms"`
		ExternalUrls struct {
			Spotify string `json:"spotify"`
		} `json:"external_urls"`
		Name string `json:"name"`
	} `json:"item"`
	IsPlaying bool `json:"is_playing"`
}

func createSpotifyWidget(currentTrack map[string]interface{}) string {
	svgTemplateBase64 := `PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iMzIwIiBoZWlnaHQ9Ijg0IiBhcmlhLWxhYmVsbGVkYnk9ImNhcmRUaXRsZSIgcm9sZT0iaW1nIj48bGluayB4bWxucz0iIiB0eXBlPSJ0ZXh0L2NzcyIgaWQ9ImRhcmstbW9kZSIgcmVsPSJzdHlsZXNoZWV0IiBocmVmPSIiLz48bGluayB4bWxucz0iIiB0eXBlPSJ0ZXh0L2NzcyIgaWQ9ImRhcmstbW9kZSIgcmVsPSJzdHlsZXNoZWV0IiBocmVmPSIiLz4KICA8dGl0bGUgaWQ9ImNhcmRUaXRsZSI+Tm93IHBsYXlpbmcgb24gU3BvdGlmeTwvdGl0bGU+CiAgPGZvcmVpZ25PYmplY3Qgd2lkdGg9IjMyMCIgaGVpZ2h0PSI4NCI+CiAgICA8c3R5bGU+CiAgICAgIGRpdiB7CiAgICAgICAgZm9udC1mYW1pbHk6IC1hcHBsZS1zeXN0ZW0sIEJsaW5rTWFjU3lzdGVtRm9udCwgU2Vnb2UgVUksIEhlbHZldGljYSwgQXJpYWwsIHNhbnMtc2VyaWYsIEFwcGxlIENvbG9yIEVtb2ppLCBTZWdvZSBVSSBFbW9qaTsKICAgICAgfQoKICAgICAgLmNvbnRhaW5lciB7CiAgICAgICAgZGlzcGxheTogZmxleDsKICAgICAgICBhbGlnbi1pdGVtczogY2VudGVyOwoKICAgICAgICBib3JkZXItcmFkaXVzOiAxMHB4OwoKICAgICAgICBwYWRkaW5nOiAxMHB4IDEwcHgKICAgICAgfQoKICAgICAgLmNvdmVyLWxpbmsgewogICAgICAgIGhlaWdodDogNjRweDsKICAgICAgfQoKICAgICAgLmNvdmVyIHsKICAgICAgICBib3JkZXItcmFkaXVzOiAxcHg7CgogICAgICAgIG1hcmdpbi1yaWdodDogMTBweDsKICAgICAgfQoKICAgICAgLnBsYXlpbmcgewogICAgICAgIGRpc3BsYXk6IGZsZXg7CiAgICAgICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7CiAgICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjsKCiAgICAgICAgY29sb3I6ICM1M2IxNGY7CiAgICAgICAgZm9udC13ZWlnaHQ6IGJvbGQ7CiAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyOwoKICAgICAgICBtYXJnaW4tYm90dG9tOiA4cHg7CiAgICAgIH0KCiAgICAgIC5ub3QtcGxheSB7CiAgICAgICAgY29sb3I6ICNmZjE2MTY7CiAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyOwoKCQltYXJnaW4tYm90dG9tOiAwOwogICAgICB9CgogICAgICAuYXJ0aXN0IHsKICAgICAgICBjb2xvcjogIzEyMTIxMjsKICAgICAgICBmb250LXdlaWdodDogNTAwOwogICAgICAgIGZvbnQtc2l6ZTogMTRweDsKCiAgICAgICAgbWFyZ2luLWJvdHRvbTogM3B4OwogICAgICB9CgogICAgICAuc29uZyB7CiAgICAgICAgY29sb3I6ICMyMTIxMjI7CiAgICAgICAgZm9udC1zaXplOiAxNHB4OwoKICAgICAgICBtYXJnaW4tYm90dG9tOiAxOHB4OwogICAgICB9CgogICAgICBAbWVkaWEgKHByZWZlcnMtY29sb3Itc2NoZW1lOiBsaWdodCkgewogICAgICAgIC5hcnRpc3R7CiAgICAgICAgICBjb2xvcjogIzEyMTIxMjsKICAgICAgICB9CgogICAgICAgIC5zb25newogICAgICAgICAgY29sb3I6ICMyMTIxMjI7CiAgICAgICAgfQogICAgICB9CgogICAgICBAbWVkaWEgKHByZWZlcnMtY29sb3Itc2NoZW1lOiBkYXJrKSB7CiAgICAgICAgLmFydGlzdHsKICAgICAgICAgIGNvbG9yOiAjZjRmNGY0OwogICAgICAgIH0KCiAgICAgICAgLnNvbmd7CiAgICAgICAgICBjb2xvcjogI2RiZGJkYzsKICAgICAgICB9CiAgICAgIH0KCiAgICAgICNiYXJzIHsKICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgICAgICAgaGVpZ2h0OiA2cHg7CiAgICAgICAgd2lkdGg6IDIyMHB4OwogICAgICAgIG92ZXJmbG93OiBoaWRkZW47CiAgICAgICAgbWFyZ2luOiAtNnB4IDAgMCAwcHg7CiAgICAgIH0KCiAgICAgIC5iYXIgewogICAgICAgIGJhY2tncm91bmQ6ICM1M2IxNGY7CiAgICAgICAgYm90dG9tOiAxcHg7CiAgICAgICAgaGVpZ2h0OiAzcHg7CiAgICAgICAgcG9zaXRpb246IGFic29sdXRlOwogICAgICAgIHdpZHRoOiAzcHg7CiAgICAgICAgYW5pbWF0aW9uOiBzb3VuZCAwbXMgLTgwMG1zIGxpbmVhciBpbmZpbml0ZSBhbHRlcm5hdGU7CiAgICAgIH0KCiAgICAgIEBrZXlmcmFtZXMgc291bmQgewogICAgICAgIDAlIHsKICAgICAgICAgIG9wYWNpdHk6IC4zNTsKICAgICAgICAgIGhlaWdodDogM3B4OwogICAgICAgIH0KCiAgICAgICAgMTAwJSB7CiAgICAgICAgICBvcGFjaXR5OiAxOwogICAgICAgICAgaGVpZ2h0OiA2cHg7CiAgICAgICAgfQogICAgICB9CgogICAgICAuYmFyOm50aC1jaGlsZCgxKSAgeyBsZWZ0OiAxcHg7IGFuaW1hdGlvbi1kdXJhdGlvbjogNDk4bXM7IH0uYmFyOm50aC1jaGlsZCgyKSAgeyBsZWZ0OiA1cHg7IGFuaW1hdGlvbi1kdXJhdGlvbjogMzg4bXM7IH0uYmFyOm50aC1jaGlsZCgzKSAgeyBsZWZ0OiA5cHg7IGFuaW1hdGlvbi1kdXJhdGlvbjogMzk1bXM7IH0uYmFyOm50aC1jaGlsZCg0KSAgeyBsZWZ0OiAxM3B4OyBhbmltYXRpb24tZHVyYXRpb246IDM1NW1zOyB9LmJhcjpudGgtY2hpbGQoNSkgIHsgbGVmdDogMTdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MzZtczsgfS5iYXI6bnRoLWNoaWxkKDYpICB7IGxlZnQ6IDIxcHg7IGFuaW1hdGlvbi1kdXJhdGlvbjogNDQ3bXM7IH0uYmFyOm50aC1jaGlsZCg3KSAgeyBsZWZ0OiAyNXB4OyBhbmltYXRpb24tZHVyYXRpb246IDM2NW1zOyB9LmJhcjpudGgtY2hpbGQoOCkgIHsgbGVmdDogMjlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzODltczsgfS5iYXI6bnRoLWNoaWxkKDkpICB7IGxlZnQ6IDMzcHg7IGFuaW1hdGlvbi1kdXJhdGlvbjogNDU5bXM7IH0uYmFyOm50aC1jaGlsZCgxMCkgIHsgbGVmdDogMzdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNzhtczsgfS5iYXI6bnRoLWNoaWxkKDExKSAgeyBsZWZ0OiA0MXB4OyBhbmltYXRpb24tZHVyYXRpb246IDM5OW1zOyB9LmJhcjpudGgtY2hpbGQoMTIpICB7IGxlZnQ6IDQ1cHg7IGFuaW1hdGlvbi1kdXJhdGlvbjogNDEzbXM7IH0uYmFyOm50aC1jaGlsZCgxMykgIHsgbGVmdDogNDlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NThtczsgfS5iYXI6bnRoLWNoaWxkKDE0KSAgeyBsZWZ0OiA1M3B4OyBhbmltYXRpb24tZHVyYXRpb246IDM3MG1zOyB9LmJhcjpudGgtY2hpbGQoMTUpICB7IGxlZnQ6IDU3cHg7IGFuaW1hdGlvbi1kdXJhdGlvbjogMzY0bXM7IH0uYmFyOm50aC1jaGlsZCgxNikgIHsgbGVmdDogNjFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NTFtczsgfS5iYXI6bnRoLWNoaWxkKDE3KSAgeyBsZWZ0OiA2NXB4OyBhbmltYXRpb24tZHVyYXRpb246IDM1Mm1zOyB9LmJhcjpudGgtY2hpbGQoMTgpICB7IGxlZnQ6IDY5cHg7IGFuaW1hdGlvbi1kdXJhdGlvbjogMzU0bXM7IH0uYmFyOm50aC1jaGlsZCgxOSkgIHsgbGVmdDogNzNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MzltczsgfS5iYXI6bnRoLWNoaWxkKDIwKSAgeyBsZWZ0OiA3N3B4OyBhbmltYXRpb24tZHVyYXRpb246IDM5OW1zOyB9LmJhcjpudGgtY2hpbGQoMjEpICB7IGxlZnQ6IDgxcHg7IGFuaW1hdGlvbi1kdXJhdGlvbjogNDMxbXM7IH0uYmFyOm50aC1jaGlsZCgyMikgIHsgbGVmdDogODVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MzJtczsgfS5iYXI6bnRoLWNoaWxkKDIzKSAgeyBsZWZ0OiA4OXB4OyBhbmltYXRpb24tZHVyYXRpb246IDM3Nm1zOyB9LmJhcjpudGgtY2hpbGQoMjQpICB7IGxlZnQ6IDkzcHg7IGFuaW1hdGlvbi1kdXJhdGlvbjogNTAwbXM7IH0uYmFyOm50aC1jaGlsZCgyNSkgIHsgbGVmdDogOTdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NjJtczsgfS5iYXI6bnRoLWNoaWxkKDI2KSAgeyBsZWZ0OiAxMDFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NjdtczsgfS5iYXI6bnRoLWNoaWxkKDI3KSAgeyBsZWZ0OiAxMDVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0ODVtczsgfS5iYXI6bnRoLWNoaWxkKDI4KSAgeyBsZWZ0OiAxMDlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0OTRtczsgfS5iYXI6bnRoLWNoaWxkKDI5KSAgeyBsZWZ0OiAxMTNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNjhtczsgfS5iYXI6bnRoLWNoaWxkKDMwKSAgeyBsZWZ0OiAxMTdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNjNtczsgfS5iYXI6bnRoLWNoaWxkKDMxKSAgeyBsZWZ0OiAxMjFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNjNtczsgfS5iYXI6bnRoLWNoaWxkKDMyKSAgeyBsZWZ0OiAxMjVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MDZtczsgfS5iYXI6bnRoLWNoaWxkKDMzKSAgeyBsZWZ0OiAxMjlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NjdtczsgfS5iYXI6bnRoLWNoaWxkKDM0KSAgeyBsZWZ0OiAxMzNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNzRtczsgfS5iYXI6bnRoLWNoaWxkKDM1KSAgeyBsZWZ0OiAxMzdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MjFtczsgfS5iYXI6bnRoLWNoaWxkKDM2KSAgeyBsZWZ0OiAxNDFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0OTBtczsgfS5iYXI6bnRoLWNoaWxkKDM3KSAgeyBsZWZ0OiAxNDVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzOThtczsgfS5iYXI6bnRoLWNoaWxkKDM4KSAgeyBsZWZ0OiAxNDlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzODZtczsgfS5iYXI6bnRoLWNoaWxkKDM5KSAgeyBsZWZ0OiAxNTNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MjFtczsgfS5iYXI6bnRoLWNoaWxkKDQwKSAgeyBsZWZ0OiAxNTdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MDJtczsgfS5iYXI6bnRoLWNoaWxkKDQxKSAgeyBsZWZ0OiAxNjFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0ODltczsgfS5iYXI6bnRoLWNoaWxkKDQyKSAgeyBsZWZ0OiAxNjVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MzNtczsgfS5iYXI6bnRoLWNoaWxkKDQzKSAgeyBsZWZ0OiAxNjlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NDFtczsgfS5iYXI6bnRoLWNoaWxkKDQ0KSAgeyBsZWZ0OiAxNzNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MDhtczsgfS5iYXI6bnRoLWNoaWxkKDQ1KSAgeyBsZWZ0OiAxNzdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MzltczsgfS5iYXI6bnRoLWNoaWxkKDQ2KSAgeyBsZWZ0OiAxODFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MTdtczsgfS5iYXI6bnRoLWNoaWxkKDQ3KSAgeyBsZWZ0OiAxODVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NzFtczsgfS5iYXI6bnRoLWNoaWxkKDQ4KSAgeyBsZWZ0OiAxODlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MzltczsgfS5iYXI6bnRoLWNoaWxkKDQ5KSAgeyBsZWZ0OiAxOTNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0ODVtczsgfS5iYXI6bnRoLWNoaWxkKDUwKSAgeyBsZWZ0OiAxOTdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNjZtczsgfS5iYXI6bnRoLWNoaWxkKDUxKSAgeyBsZWZ0OiAyMDFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MDZtczsgfS5iYXI6bnRoLWNoaWxkKDUyKSAgeyBsZWZ0OiAyMDVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MThtczsgfS5iYXI6bnRoLWNoaWxkKDUzKSAgeyBsZWZ0OiAyMDlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0ODFtczsgfS5iYXI6bnRoLWNoaWxkKDU0KSAgeyBsZWZ0OiAyMTNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MTFtczsgfS5iYXI6bnRoLWNoaWxkKDU1KSAgeyBsZWZ0OiAyMTdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNjZtczsgfS5iYXI6bnRoLWNoaWxkKDU2KSAgeyBsZWZ0OiAyMjFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0ODhtczsgfS5iYXI6bnRoLWNoaWxkKDU3KSAgeyBsZWZ0OiAyMjVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NjhtczsgfS5iYXI6bnRoLWNoaWxkKDU4KSAgeyBsZWZ0OiAyMjlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NzBtczsgfS5iYXI6bnRoLWNoaWxkKDU5KSAgeyBsZWZ0OiAyMzNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NzVtczsgfS5iYXI6bnRoLWNoaWxkKDYwKSAgeyBsZWZ0OiAyMzdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NTVtczsgfS5iYXI6bnRoLWNoaWxkKDYxKSAgeyBsZWZ0OiAyNDFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NDhtczsgfS5iYXI6bnRoLWNoaWxkKDYyKSAgeyBsZWZ0OiAyNDVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NTJtczsgfS5iYXI6bnRoLWNoaWxkKDYzKSAgeyBsZWZ0OiAyNDlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0ODhtczsgfS5iYXI6bnRoLWNoaWxkKDY0KSAgeyBsZWZ0OiAyNTNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzOTltczsgfS5iYXI6bnRoLWNoaWxkKDY1KSAgeyBsZWZ0OiAyNTdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MzVtczsgfS5iYXI6bnRoLWNoaWxkKDY2KSAgeyBsZWZ0OiAyNjFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNjNtczsgfS5iYXI6bnRoLWNoaWxkKDY3KSAgeyBsZWZ0OiAyNjVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0ODdtczsgfS5iYXI6bnRoLWNoaWxkKDY4KSAgeyBsZWZ0OiAyNjlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNTVtczsgfS5iYXI6bnRoLWNoaWxkKDY5KSAgeyBsZWZ0OiAyNzNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NDBtczsgfS5iYXI6bnRoLWNoaWxkKDcwKSAgeyBsZWZ0OiAyNzdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NzNtczsgfS5iYXI6bnRoLWNoaWxkKDcxKSAgeyBsZWZ0OiAyODFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNjBtczsgfS5iYXI6bnRoLWNoaWxkKDcyKSAgeyBsZWZ0OiAyODVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NDJtczsgfS5iYXI6bnRoLWNoaWxkKDczKSAgeyBsZWZ0OiAyODlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MTNtczsgfS5iYXI6bnRoLWNoaWxkKDc0KSAgeyBsZWZ0OiAyOTNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNTNtczsgfS5iYXI6bnRoLWNoaWxkKDc1KSAgeyBsZWZ0OiAyOTdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNzJtczsgfS5iYXI6bnRoLWNoaWxkKDc2KSAgeyBsZWZ0OiAzMDFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzOTltczsgfS5iYXI6bnRoLWNoaWxkKDc3KSAgeyBsZWZ0OiAzMDVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MTNtczsgfS5iYXI6bnRoLWNoaWxkKDc4KSAgeyBsZWZ0OiAzMDlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNzVtczsgfS5iYXI6bnRoLWNoaWxkKDc5KSAgeyBsZWZ0OiAzMTNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0OTJtczsgfS5iYXI6bnRoLWNoaWxkKDgwKSAgeyBsZWZ0OiAzMTdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzOTRtczsgfS5iYXI6bnRoLWNoaWxkKDgxKSAgeyBsZWZ0OiAzMjFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MTBtczsgfS5iYXI6bnRoLWNoaWxkKDgyKSAgeyBsZWZ0OiAzMjVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MTltczsgfS5iYXI6bnRoLWNoaWxkKDgzKSAgeyBsZWZ0OiAzMjlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNTZtczsgfS5iYXI6bnRoLWNoaWxkKDg0KSAgeyBsZWZ0OiAzMzNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NTVtczsgfS5iYXI6bnRoLWNoaWxkKDg1KSAgeyBsZWZ0OiAzMzdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MTVtczsgfS5iYXI6bnRoLWNoaWxkKDg2KSAgeyBsZWZ0OiAzNDFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzNzltczsgfS5iYXI6bnRoLWNoaWxkKDg3KSAgeyBsZWZ0OiAzNDVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzOThtczsgfS5iYXI6bnRoLWNoaWxkKDg4KSAgeyBsZWZ0OiAzNDlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0ODRtczsgfS5iYXI6bnRoLWNoaWxkKDg5KSAgeyBsZWZ0OiAzNTNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MTRtczsgfS5iYXI6bnRoLWNoaWxkKDkwKSAgeyBsZWZ0OiAzNTdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NzNtczsgfS5iYXI6bnRoLWNoaWxkKDkxKSAgeyBsZWZ0OiAzNjFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MTFtczsgfS5iYXI6bnRoLWNoaWxkKDkyKSAgeyBsZWZ0OiAzNjVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0ODZtczsgfS5iYXI6bnRoLWNoaWxkKDkzKSAgeyBsZWZ0OiAzNjlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MzdtczsgfS5iYXI6bnRoLWNoaWxkKDk0KSAgeyBsZWZ0OiAzNzNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MTdtczsgfS5iYXI6bnRoLWNoaWxkKDk1KSAgeyBsZWZ0OiAzNzdweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiAzODRtczsgfS5iYXI6bnRoLWNoaWxkKDk2KSAgeyBsZWZ0OiAzODFweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NTdtczsgfS5iYXI6bnRoLWNoaWxkKDk3KSAgeyBsZWZ0OiAzODVweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0ODRtczsgfS5iYXI6bnRoLWNoaWxkKDk4KSAgeyBsZWZ0OiAzODlweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0MTltczsgfS5iYXI6bnRoLWNoaWxkKDk5KSAgeyBsZWZ0OiAzOTNweDsgYW5pbWF0aW9uLWR1cmF0aW9uOiA0NTltczsgfS5iYXI6bnRoLWNoaWxkKDEwMCkgIHsgbGVmdDogMzk3cHg7IGFuaW1hdGlvbi1kdXJhdGlvbjogNDE2bXM7IH0KICAgIDwvc3R5bGU+CiAgICA8ZGl2IHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hodG1sIiBjbGFzcz0iY29udGFpbmVyIj4KICAgICAgICAKICAgICAgICAgIDxhIGhyZWY9Int7dXJsfX0iIHRhcmdldD0iX0JMQU5LIiBjbGFzcz0iY292ZXItbGluayI+CiAgICAgICAgICAgIDxpbWcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGh0bWwiIHNyYz0iZGF0YTppbWFnZS9wbmc7YmFzZTY0LCB7e2ltZ319IiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIGNsYXNzPSJjb3ZlciIgLz4KICAgICAgICAgIDwvYT4KICAgICAgICAKICAgICAgICA8ZGl2IGNsYXNzPSJ0ZXh0LWNvbnRhaW5lciI+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJhcnRpc3QiPnt7YXJ0aXN0c319IDwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0ic29uZyI+e3tzb25nfX08L2Rpdj4KICAgICAgICAgIDxkaXYgaWQ9ImJhcnMiPjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PGRpdiBjbGFzcz0iYmFyIj48L2Rpdj48ZGl2IGNsYXNzPSJiYXIiPjwvZGl2PjxkaXYgY2xhc3M9ImJhciI+PC9kaXY+PC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICA8L2Rpdj4KICA8L2ZvcmVpZ25PYmplY3Q+Cjwvc3ZnPg==` // This contains the template for the SVG that will be returned to the user.

	svgTemplateBytes, _ := base64.StdEncoding.DecodeString(svgTemplateBase64)
	svgTemplate := string(svgTemplateBytes)

	trimName := func(name string) string {
		if len(name) > 35 {
			return name[:35] + "..."
		}
		return name
	}

	svgTemplate = strings.Replace(svgTemplate, "{{url}}", currentTrack["url"].(string), -1)
	svgTemplate = strings.Replace(svgTemplate, "{{artists}}", currentTrack["artists"].(string), -1)
	svgTemplate = strings.Replace(svgTemplate, "{{song}}", trimName(currentTrack["title"].(string)), -1)

	imageURL := currentTrack["image"].(string)
	resp, err := http.Get(imageURL)
	if err != nil {
		return ""
	}

	defer resp.Body.Close()

	img, _ := io.ReadAll(resp.Body)
	imgBase64 := base64.StdEncoding.EncodeToString(img)

	svgTemplate = strings.Replace(svgTemplate, "{{img}}", imgBase64, -1)

	return svgTemplate
}
